# Random Sampling Functions of PyTorch tensors

### Five amazing functions to generate random tensors following a certain mathematical criteria

PyTorch is an open source machine learning library based on the Torch library, used for applications such as computer vision and natural language processing, primarily developed by Facebook's AI Research lab. 
Random sampling is a part of the sampling technique in which each sample has an equal probability of being chosen.
There are many random sampling functions in PyTorch, here are five of them - 

- torch.bernoulli(input, *, generator = None, out = None) 
- torch.poisson(input *, generator=None)
- torch.randn(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
- torch.normal(mean, std, *, generator=None, out=None)
- torch.randperm(n, out=None, dtype=torch.int64, layout=torch.strided, device=None, requires_grad=False)

In [1]:
# Import torch and other required modules
import torch
import numpy as np

ModuleNotFoundError: No module named 'torch'

## Function 1 - torch.bernoulli(input, *, generator = None, out = None)

Draws binary random numbers (0 or 1) from a Bernoulli distribution.

The 'input' tensor should be a tensor containing probabilities to be used for drawing the binary random number. Hence, all values in 'input' have to be in the range: 0 <= input <= 1

#### out = Bernoulli( p = input )

The returned 'out' tensor only has values 0 or 1 and is of the same shape as input.

In [7]:
# Example 1 - 
a = torch.empty(3, 3).uniform_(0, 1) #generate uniform random matrix 'a' with range[0, 1]
print(a) 
print(torch.bernoulli(a)) #


tensor([[0.0447, 0.5555, 0.4990],
        [0.0247, 0.0872, 0.5015],
        [0.4357, 0.4409, 0.1197]])
tensor([[0., 1., 1.],
        [0., 0., 0.],
        [1., 1., 0.]])


Calculates(the function) benoulli distribution of each element of above generated matrix considering them as probabilities, and gives out a tensor.


In [9]:
a = torch.ones(3,3) # a tensor of 3 * 3 size - 
torch.bernoulli(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Probability of generating 1 is 1 in Bernoulli Distribution

In [10]:
# Example 3 - breaking (to illustrate when it breaks)
a = torch.zeros(3, 3)
torch.bernoulli(a)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Probability of generating 1 is 1 in Bernoulli Distribution

Suppose in a case you want to generate a random tensor which has value 0 or 1 depending on already existing probability matrix, use this.

## torch.poisson(input *, generator=None)

Returns a tensor of the same size as input with each element sampled from a Poisson distribution with rate parameter given by the corresponding element in input i.e. 

### out = poisson(input)

In [13]:
a = torch.rand(3, 3) * 5#
print(a) #rate parameter within the range[0, 5]

torch.poisson(a)

tensor([[1.3610, 4.4428, 2.6187],
        [2.7940, 2.9064, 0.7345],
        [0.7289, 1.3983, 0.1674]])


tensor([[1., 5., 4.],
        [2., 0., 0.],
        [1., 1., 0.]])

Returns a tensor with values selected randomly in accordance to Poisson Distribution.

In [14]:
a = torch.zeros(3,3)
torch.poisson(a)# Example 2 - working

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Poisson distribution of zero matrix is zero

In [50]:
b = torch.ones(3,3)  # Example 3 - breaking (to illustrate when it breaks)
a = b * 0.0
c = (torch.poisson(a)) 

print(torch.poisson(torch.arange(0,3)))

RuntimeError: ignored

Type error.

Use this function when you want to get a tensor of Poisson Distribution with given rate parameter matrix

##torch.randn(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

Returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1

###out = N(0, 1)

In [21]:
torch.randn(4)

tensor([-0.3167,  1.3979, -0.2526, -1.3775])

A one dimensional tensor filled with randomly generated numbers with mean = 0 and variance = 1

In [22]:
torch.randn(3, 4)

tensor([[-1.5710,  0.7825,  1.1446,  0.5504],
        [-0.1652,  0.7153, -0.2777,  0.4556],
        [ 0.5884,  0.0305,  1.4255, -2.0634]])

A two dimensional tensor filled with randomly generated numbers with mean = 0 and variance = 1

In [40]:
torch.randn(3, 4, 4.)# Example 3 - breaking (to illustrate when it breaks)

TypeError: ignored

All dimensions have to be integer type, ofcourse because there's no such thing 6.2 number of rows, etc.

When you want to generate a sample of digits within a range.

---



## torch.normal(mean, std, *, generator=None, out=None)

Returns a tensor of random numbers drawn from separate normal distributions whose mean and standard deviation are given.


The mean is a tensor with the mean of each output element’s normal distribution


The std is a tensor with the standard deviation of each output element’s normal distribution


The shapes of mean and std don’t need to match, but the total number of elements in each tensor need to be the same.


When the shapes do not match, the shape of mean is used as the shape for the returned output tensor

In [26]:
 torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))

tensor([ 1.0673,  1.8146,  3.0028,  2.5649,  4.9581,  5.9722,  6.6318,  8.0591,
         9.0492, 10.1381])

Here, mean is is in range : (1, 11) and since the no of elements in mean and std tensors are not same, we get a tensor having same no of elements as the number of elements in mean tensor

In [36]:
torch.normal(mean = 0.1, std = torch.arange(0, 11.0))

tensor([ 0.1000,  0.8545,  2.7312, -2.7569,  0.9138, -7.5564, -2.0368,  6.1219,
        11.0975,  1.6669,  6.5510])

Here, since mean is common,  it is used for every element in std tensor

In [38]:
torch.normal(mean = 0.1, std = 0.1)

TypeError: ignored

Both can't be can't be fixed at the same time, one should be a tensor atleast

You should consider using this function when you want to fit a tensor with a data with certain mean(s) and distribution(s).




##torch.randperm(n, out=None, dtype=torch.int64, layout=torch.strided, device=None, requires_grad=False)

Returns a random permutation of integers between 0 and n-1

In [39]:
torch.randperm(4)

tensor([3, 2, 0, 1])

Generate a random tensor of having a permutation of digits in range [0, n)

In [46]:
torch.randperm(5, dtype = torch.float32)# Example 2 - working

tensor([4., 2., 1., 0., 3.])

You can change dtype of output tensor

In [47]:
torch.randperm(-1)# Example 3 - breaking (to illustrate when it breaks)

RuntimeError: ignored

Can't pass in negative value in randperm

Closing comments about when to use this function

## Conclusion

Long story short, if you want to generate a tensor with random elemensts, start by finding what do you wanna do those integers with, generally, torch.randn() in itself is enough for most normal purposes, but PyTorch doesn't leave you on your own if you have certain other use cases. The above provided list is in no way exhaustive.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html


In [1]:
!pip install jovian --upgrade --quiet

In [51]:
import jovian

ModuleNotFoundError: ignored

In [0]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
